# Generated by Django 3.0.2 on 2020-04-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiveproduct',
            old_name='price_per_crate',
            new_name='r_price_per_crate',
        ),
    ]
