# Generated by Django 3.0.2 on 2020-04-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200406_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleproduct',
            old_name='total_price',
            new_name='sale_total_price',
        ),
    ]
