# Generated by Django 3.0.2 on 2020-12-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201205_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlevolume',
            name='bottle_capacity',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
